### ISSUE TITLE
如果可以能把sql文件发出来吗

### ISSUE THREAD

**Issue by findingwch** [AlexhahahaDrag/alex_miaosha#2]

**Comment by AlexhahahaDrag** [comment]
我最近整理一下，这块除了mysql之外还需要nacos、redis等。我最近整理一个文档

**Comment by AlexhahahaDrag** [comment]
![image](https://github.com/AlexhahahaDrag/alex_miaosha/assets/40189082/09c3a304-31db-4797-a8ba-4d45e82761b1)
sql在这个文件下面

**Comment by AlexhahahaDrag** [comment]
已添加sql文件
